// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ICategoryService.cs" company="EPAM Systems">
//   Copyright 2015
// </copyright>
// <summary>
//   Autogenerated Web Services
// </summary>
// --------------------------------------------------------------------------------------------------------------------
namespace frmworkPKC.Services
{
	using Entities;
	using frmworkPKC.Service.Pattern;

    /// <summary>
    /// The category service interface
    /// </summary>
    public interface ICategoryService : IService<Category>
    { }
}
