// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ISupplierRepository.cs" company="EPAM Systems">
//   Copyright 2015
// </copyright>
// <summary>
//   Autogenerated Web Services
// </summary>
// --------------------------------------------------------------------------------------------------------------------
namespace frmworkPKC.Repository
{
	using Entities;
	using global::frmworkPKC.Repository.Pattern.Repositories;

    /// <summary>
    /// The supplier Repository interface
    /// </summary> 
    public interface ISupplierRepository : IRepositoryAsync<Supplier>
    { }   
}
