// --------------------------------------------------------------------------------------------------------------------
// <copyright file="CategoryService.cs" company="EPAM Systems">
//   Copyright 2015
// </copyright>
// <summary>
//   Autogenerated Web Services
// </summary>
// --------------------------------------------------------------------------------------------------------------------
namespace frmworkPKC.Services
{
    using Entities;
    using Repository;
    using frmworkPKC.Service.Pattern;
	
	/// <summary>
    /// The category service.
    /// </summary>
    public class CategoryService : Service<Category>, ICategoryService
    { 
		/// <summary>
        /// The repository asynchronous
        /// </summary>
		private readonly ICategoryRepository repositoryAsync;
    
        /// <summary>
        /// Initializes a new instance of the <see cref="CategoryService"/> class.
        /// </summary>
        /// <param name="repository">
        /// The async repository.
        /// </param>

        public CategoryService(ICategoryRepository repository)
            : base(repository)
        {
		    this.repositoryAsync = repository;
        }
	}
}
